//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LN.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifidedBy { get; set; }
        public Nullable<System.Guid> PositionID { get; set; }
        public byte[] Image { get; set; }
    }
}
