//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LN.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingField
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> FieldID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> BeginTime { get; set; }
        public Nullable<int> EndTime { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ThruDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifidedBy { get; set; }
    }
}
